version: "3.9"

services:
  note:
    image: 'note:latest'
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3443:3443
    environment:
      - 'POSTGRES_HOST: localhost'
      - 'RABBIT_HOST: localhost'

  profile:
    image: 'profile:latest'
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3444:3444
    environment:
      - 'POSTGRES_HOST: localhost'
      - 'RABBIT_HOST: localhost'

  postgres:
    image: 'postgres:14.2'
    environment:
      - 'POSTGRES_DB=notes'
      - 'POSTGRES_PASSWORD=1'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - ~/postgres124:/var/lib/postgresql/data


  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=1'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - "5672:5672"

  ui:
    image: 'ui:latest'
    ports:
      - "3000:3000"
    depends_on:
      - note
      - profile
      - postgres
      - rabbitmq
