spring.application.name=yad-integration

#SECURITY
spring.security.user.name=admin
spring.security.user.password=admin

#SERVER
server.port=3444

#VARIABLES
yad.clientId=${YAD_CLIENT_ID}
yad.secret=${YAD_SECRET}
